### PR TITLE
Apply sort order to stock plate retrieval

### LINKED ISSUE #619: BUG - Inconsistent stock plate ids used on lables
**Describe the bug**
Limber usually uses the stock plate barcode as a consistent tracking number through the whole process.
In the case of the LTHR process this is complicated by the pooling upfront.
This is resulting in inconsistencies, especially at the pooling to tubes, in which the stock plate barcode used on the plate differs from that that gets assigned to the tube name.

**RT Ticket Number**
#711295

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by JamesGlover**
Stock plate ordering was not specified, so was dependant on the
behaviour of the sequencescape database. This was resulting in
stock plates appearing to change.

This brings the behaviour mostly in line with Sequencescape, although
uses id over created at. This has the advantage of higher resolution,
quicker speed, and not needing a new sort scope added.

That said, we should probably make the same change within sequencescape.

Fixes #619

Closes #

Changes proposed in this pull request:

*
*
* ...

### CODE REVIEW

File: app/sequencescape/sequencescape/api/v2/plate.rb [hunk 1]
```diff
@@ -97,7 +97,7 @@ def stock_plates(purpose_names: SearchHelper.stock_plate_names)
   end
 
   def stock_plate
-    stock_plates.last
+    stock_plates.order(id: :asc).last
   end
```
Comment (JamesGlover) [inline app/sequencescape/sequencescape/api/v2/plate.rb:101]: The fix

File: spec/sequencescape/api/v2/plate_spec.rb [hunk 2]
```diff
@@ -9,13 +9,17 @@
...
     end
+
     before do
-      allow(plate).to receive(:stock_plates).and_return(stock_plates)
+      ancestor_scope = instance_double('JsonApiClient::Query::Builder')
+      allow(plate).to receive(:stock_plates).and_return(ancestor_scope)
+      expect(ancestor_scope).to receive(:order).with(id: :asc).and_return(stock_plates)
     end
+
     it 'returns the last element of the stock plates list' do
```
Comment (JamesGlover) [inline spec/sequencescape/api/v2/plate_spec.rb:23]: Feels a bit like I'm over-mocking here, but never worked out the best way of dealing with mocking the JsonApiClient.

**Review by emrojo — APPROVED** [review]

File: spec/sequencescape/api/v2/plate_spec.rb (hunk 2 above)
Comment (KatyTaylor) [reply spec/sequencescape/api/v2/plate_spec.rb:23]: It can be horrible, I agree

**Review by KatyTaylor — APPROVED** [review]
