### PR TITLE
DPL-983: Handle page errors

### LINKED ISSUE #1462: DPL-983 [BUG] Sample arraying page error handling
**Describe the bug**
The sample arraying page in the scRNA Core Cell Extraction pipeline (when creating the LRC Blood Bank plate) does not handle error responses from Sequencescape correctly. Example described below.

**To Reproduce**
Steps to reproduce the behaviour:
1. In SS, go to Studies > Inactive (link on left) > select any study in the list
2. Click Sample Manifests (link on right) > Create manifest for tubes
3. Template = "scRNA Core", Purpose = "LRC Blood Vac", Supplier = anything, click "Create manifest..."
4. Click "Download blank manifest"
5. Open the spreadsheet, fill out the 3 mandatory (red) fields with anything, save.
6. Back in SS on the same page, upload the completed manifest.
7. Open the manifest by clicking on the link in the 'Name' column
8. Copy the barcode under "Barcodes"
9. Search for the barcode in Limber
10. Click "Add an empty LRC Blood Aliquot tube"
11. Click "Manual transfer"
12. Copy the barcode from the success message and search for it
13. Copy the barcode again and save it somewhere
14. Click "Add an empty LRC Blood Bank" plate
15. Paste the saved barcode into one of the boxes and click off the field
16. Open the JS console
17. Click "Create"
18. See error in JS console - 400 bad request, with message {"message":[["Submission Study is not active"],"Failed to create submission"]}
19. Desired behaviour - a useful error message should be shown to the user, instead of it failing silently.

**Screenshots**
Screenshot 2023-11-14 at 14 58 32

### PR DESCRIPTION
**Pull request by StephenHulme**
Closes #1462

#### Changes proposed in this pull request

- Implement JS alert and request error feedback system using Vue components
- Create alerts when an error occurs on a request

Multiple alerts are handled:
Screenshot 2023-11-21 at 15 54 30

The error that generated this story is now being handled:
Screenshot 2023-11-21 at 15 56 33

#### Notes

- Incidently, this is a partial solution to #836
- Some of these errors should be caught _much_ earlier in the pipeline

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: app/javascript/shared/components/Alert.vue [hunk 1]
```diff
@@ -0,0 +1,19 @@
+<template>
+  <div :class="['alert', `alert-${level}`, 'alert-dismissible', 'fade', 'show']" role="alert">
+    <strong>{{ title }}:</strong> {{ message }}
+    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
```
Comment (BenTopping) [inline app/javascript/shared/components/Alert.vue:4]: This is quite neat. When you close it does it also remove it from the alerts array in Page.vue?

File: app/javascript/shared/requestHelpers.js [hunk 2]
```diff
@@ -28,4 +29,15 @@ const requestsFromPlates = function (plateObjs) {
   return requestsArray
 }
 
-export { requestIsActive, requestsFromPlates, requestIsLibraryCreation }
+const handleFailedRequest = function (request) {
+  // generate an alert on the page
+  const title = request.response.data.message[1]
+  const messages = request.response.data.message[0].join(', ')
+  eventBus.$emit('push-alert', {
```
Comment (BenTopping) [inline app/javascript/shared/requestHelpers.js:36]: Without a state manager this seems like the best way to handle the cross-component error handling, nice 👍

File: app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue [hunk 3]
```diff
@@ -597,10 +598,10 @@ export default {
         })
         .catch((error) => {
           // Something has gone wrong
-          this.loading = false
           // TODO Replace this with generic limber logging when available
```
Comment (BenTopping) [inline app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue:601]: Can probably remove this comment?

File: app/javascript/shared/components/Page.vue
Comment (BenTopping) [inline app/javascript/shared/components/Page.vue:1]: Worth adding tests to Page.spec.js  to check the behaviour of alerts, multiple alerts etc.

**Review by BenTopping — COMMENTED** [review]
Nice solution 👌. Couple small comments / questions.

File: app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue (hunk 3 above)
Comment (BenTopping) [reply app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue:601]: Sure makes sense. I may be wrong but I don't think think its possible to log to system level with these js files since they are client-side so not sure how an integration like that would work.

**Review by BenTopping — APPROVED** [review]
LGTM
