### PR TITLE
Y24-396: Refactor Automatic State Changers

### LINKED ISSUE #2002: [BUG] Cancelling a PBMC tube
**Describe the bug**
scRNA Core - Seena, Abby and I noticed when testing the step LRC PBMC Bank --> LRC Bank Seq/Spare that if you try to cancel one of the child tubes, it throws an unhandled exception:
```
A NoMethodError occurred in tubes#update:

  undefined method `wells' for #<Sequencescape::Api::V2::Tube:@attributes={"type"=>"tubes", "id"=>"26836486", "uuid"=>"8d4c2fea-6fd3-11ef-a088-0242c6483a9e", "name"=>"SEQ:NT1790211P:A1", "labware_barcode"=>#<LabwareBarcode:0x00007fdf522da8c8 @human="ED21224878", @machine="ED21224878", @ean13="">, "state"=>"passed", "created_at"=>2024-09-11 01:19:47 +0100, "updated_at"=>2024-09-11 01:19:47 +0100}>
  app/models/state_changers.rb:43:in `contents_for'
```

### PR DESCRIPTION
**Pull request by StephenHulme**
Closes #2002 

#### Changes proposed in this pull request

- Refactor labware state changers to be specialised by labware and use mixins for alternative behaviour
  - Solves bug where a tube thinks it's a plate and calls the `contents_for` method of `DefaultStateChanger` which was originally designed for plates and not tubes
- Refactor and add state changer unit tests 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: spec/models/state_changers_spec.rb [hunk 1]
```diff
@@ -30,114 +147,146 @@
...
-        it 'changes plate state and triggers a work completion' do
-          subject.move_to!(target_state, reason, customer_accepts_responsibility)
+      it 'changes tube state and triggers a work completion' do
+        subject.move_to!(target_state, reason, customer_accepts_responsibility)
 
-          expect(work_completion_creation).to have_been_made.once
-        end
+        expect(work_completion_creation).to have_been_made.once
       end
+    end
```
[the remark this answers is not in the document]
Comment (andrewsparkes) [reply spec/models/state_changers_spec.rb:237]: I don't know what's happening here. 
Tube Aggregation is NOT a thing and there shouldn't be tests for tube aggregation. It's only ever done with plates. Aggregation is consolidating plates with few active sample wells together, to create fuller plates.

**Review by andrewsparkes — CHANGES_REQUESTED** [review]
Think this needs discussion re: tube aggregation
Plus I'm also touching this file in the tuberacks story Y24-099 to add a tube rack state changer.

File: app/models/state_changers.rb [hunk 2]
```diff
@@ -111,81 +171,46 @@ def labware
...
+  # This version of the AutomaticLabwareStateChanger is used by TubeRacks.
+  class AutomaticTubeRackStateChanger < TubeRackStateChanger
+    include AutomaticBehaviour
+
     def v2_labware
-      @v2_labware ||= Sequencescape::Api::V2.tube_for_completion(labware_uuid)
+      @v2_labware ||= Sequencescape::Api::V2.tube_rack_for_completion(labware_uuid)
     end
 
     def labware
```
Comment (andrewsparkes) [inline app/models/state_changers.rb:203]: this labware vs v2_labware nonsense will hopefully get refactored out in a later story!

File: spec/factories/purpose_config_factories.rb [hunk 3]
```diff
@@ -340,6 +340,13 @@
         name { 'Pool tube' }
         creator_class { 'LabwareCreators::PooledTubesFromWholeTubes' }
       end
+
+      # Configuration for an aggregation tube (this is _not_ a thing)
+      factory :aggregation_tube_purpose_config do
```
Comment (andrewsparkes) [inline spec/factories/purpose_config_factories.rb:345]: what's this factory used for again? doesn't seem to be mentioned elsewhere in this PR.
plus as we discussed before it's going to confuse anyone who searches for 'Aggregation' as it is definitely not a thing that is done with tubes

File: spec/factories/tube_factories.rb [hunk 4]
```diff
@@ -152,6 +152,17 @@
         transient { custom_metadatum_collection { create :custom_metadatum_collection } }
       end
     end
+
+    # Sets up a tube at the beginning of the pipeline process
+    # with two submissions of two requests each
+    factory :v2_tube_with_submissions_and_requests do
+      transient do
+        purpose_name { 'Limber Bespoke Aggregation' }
+        request_factory { :aggregation_request }
```
Comment (andrewsparkes) [inline spec/factories/tube_factories.rb:161]: please use something other than aggregation, it's a plate only thing

**Review by andrewsparkes — CHANGES_REQUESTED** [review]
Looks really good, I just don't like the tube aggregation references

File: spec/models/state_changers_spec.rb [hunk 5]
```diff
@@ -70,122 +72,181 @@
...
 
-          it 'returns the coordinates of tubes not in failed state' do
-            expect(subject.contents_for(target_state)).to eq(%w[B1 C1])
-            subject.move_to!(target_state, reason, customer_accepts_responsibility)
-          end
-        end
+    before do
+      stub_v2_tube_rack(tube_rack)
+
+      # allow(labware).to receive(:racked_tubes).and_return([racked_tube1, racked_tube2, racked_tube3])
```
Comment (andrewsparkes) [inline spec/models/state_changers_spec.rb:171]: delete if not needed

File: spec/models/state_changers_spec.rb [hunk 6]
```diff
@@ -70,122 +72,181 @@
...
+      let(:coordinates_to_pass) { [] }
+
+      before do
+        # stub_v2_tube_rack(tube_rack)
+        allow(labware).to receive(:racked_tubes).and_return([racked_tube1])
       end
+
+      # if all the tubes are already in the target state expect contents to be empty
+      # TODO: I'm not sure this is correct behaviour, it should probably raise an error
+      # or a validation should catch that the state change is not needed
```
Comment (andrewsparkes) [inline spec/models/state_changers_spec.rb:184]: I've seen this before in code on the sequencescape side. It gets an api call for a state change but then has code that works out nothing needs doing. Waste of an api call.
Not sure how that even gets triggered though. If there's a button that triggers a state change that isn't needed, then the button should not be visible (i.e. validation like you said).
Maybe someone decided it was too expensive to pull all the information into Limber and instead let SS decide?

File: spec/support/api_url_helper.rb [hunk 7]
```diff
@@ -271,14 +271,20 @@ def stub_v2_tag_layout_templates(templates)
     end
 
     # Builds the basic v2 tube finding query.
-    def stub_v2_tube(tube, stub_search: true, custom_query: nil, custom_includes: nil)
+    def stub_v2_tube(tube, stub_search: true, custom_query: nil, custom_includes: false) # rubocop:todo Metrics/AbcSize
```
Comment (andrewsparkes) [inline spec/support/api_url_helper.rb:274]: I tend to use rubocop:disable / enable over todo if I am happy with the code and have no intention of coming back to it(!)

**Review by andrewsparkes — APPROVED** [review]
Minor questions. 
Otherwise a big improvement, thanks.
