### PR TITLE
Y24-197 GBS - allow well failing on PCR1 plate

### LINKED ISSUE #1781: Y24-197 - Add fail feature to start of GBS pipeline
As GSLP Operational Lead (Anna) responsible for the operation of the GBS pipeline we would like the ability to fail wells in the "SWGA Stock" and/ or in the "GBS PCR 1" plate similar to the Heron 384 pipeline.

Context
We have processed GBS Plasmodium samples that could/should have been failed upstream, post extraction. However the samples have continued through the pipeline, sequenced and results sent to partners. The repeat work (6x months after) has now been processed and we have come to find duplicate samples data sets.

Example of where we would like to implement a fail feature
Problem plate: SQPP-15788-1-N
GBS_fail_feature_low_ng
Within the QC tab on Sequencescape "quantity in ng"  the drop out in row C can be seen.
It is at this stage in the process, when verifying the quant data that we would like to ability to fail wells in the "SWGA Stock plate" and/ or at the "GBS PCR 1"

**Who are the primary contacts for this story**
Anna(ag25)

**Who is the nominated tester for UAT**
Anna(ag25)

### PR DESCRIPTION
**Pull request by andrewsparkes**
Closes #1781 

#### Changes proposed in this pull request
- adds a new presenter for PCR that allows well failing

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: app/models/presenters/pcr_with_primer_panel_plate_presenter.rb [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  # This was specifically requested by the lab team for the GBS pipleine PCR1 plate so they
+  # could fail wells. If well failing functionality was allowed on stock plates in future, that would be a
+  # preferable option for them and they could fail the wells on the parent plate, and the PCR1 plate could
+  # be returned to using the MinimalPcrPlatePresenter.
+  class PcrWithPrimerPanelPlatePresenter < StandardPresenter
+    include HasPrimerPanel
+    self.summary_partial = 'labware/plates/pcr_with_primer_panel_summary'
+    self.state_transition_name_scope = :pcr
+
+    # summary_items is a hash of a label label, and a symbol representing the
```
Comment (KatyTaylor) [inline app/models/presenters/pcr_with_primer_panel_plate_presenter.rb:16]: label label?

**Review by KatyTaylor — APPROVED** [review]
Looks good apart from a typo in a comment I think. Just curious - did you have a conversation with the users at all to understand whether they liked not having the plate visual on the page?

File: app/models/presenters/pcr_with_primer_panel_plate_presenter.rb (hunk 1 above)
Comment (andrewsparkes) [reply app/models/presenters/pcr_with_primer_panel_plate_presenter.rb]: fixed (in 3 presenters)
