### PR TITLE
fix: disallow pending tubes when tube duplicates are allowed

### LINKED ISSUE #1437: DPL-963 [BUG] Don't allow 'pending' tubes to progress
**Describe the bug**
In the sample arraying screen in the scRNA Core Cell Extraction pipeline (transfer from LRC Blood Aliquot to LRC Blood Bank), it doesn't error if you scan in tubes that are in a 'pending' state.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make an LRC Blood Vac tube using the UAT Actions tab in Sequencescape.
2. Scan it into Limber
3. Click 'Add an empty Blood Aliquot tube'
4. Save the barcode somewhere NT1686895U
5. Make a second LRC Blood Vac tube using the UAT Actions tab in Sequencescape.
6. Scan it into Limber
7. Click 'Add an empty Blood Aliquot tube'
8. Click 'Manual Transfer'
9. Go back to the tube page (copy the barcode from the message and search for it again)
10. Save the barcode somewhere NT1686897W
11. Click 'Add an empty LRC Blood Bank plate'
12. Paste the two barcodes you saved into the boxes
13. Click 'Create'
14. Expected behaviour: it should error, saying something like 'These tubes are not yet passed: <barcode>'
15. Actual behaviour: it saves

### PR DESCRIPTION
**Pull request by StephenHulme**
Closes #1437 

#### Changes proposed in this pull request

- Refactor handling of validators to apply pending state check in all cases
- Refactor and add tests to reflect this

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: app/javascript/multi-stamp-tubes/components/MultiStampTubes.vue [hunk 1]
```diff
@@ -214,11 +215,14 @@ export default {
       return filterProps.tubeFields
     },
     scanValidation() {
-      if (this.allowTubeDuplicates === 'true') {
-        return [validScanMessage]
+      const validators = [checkState(['passed'])]
+
+      // If the user has selected to allow tube duplicates, we don't need to check for them
+      if (this.allowTubeDuplicates !== true) {
```
Comment (andrewsparkes) [inline app/javascript/multi-stamp-tubes/components/MultiStampTubes.vue:221]: maybe
```
return validators if(this.allowTubeDuplicates)

const currTubes = this.tubes.map((tubeItem) => tubeItem.labware)
validators.push(checkDuplicates(currTubes))

return validators
```
